version: 1
disable_existing_loggers: true

formatters:
    with_time:
        format: "[%(asctime)s][%(name)s:%(levelname)s] %(message)s"
    without_time:
        format: "[%(name)s:%(levelname)s] %(message)s"

filters:
    level:
        (): fsb.logger.LevelFilter
        level: WARNING

handlers:
    stdout_app:
        class: logging.StreamHandler
        level: NOTSET
        formatter: without_time
        filters: [level]
        stream: ext://sys.stdout
    stderr_app:
        class: logging.StreamHandler
        level: WARNING
        formatter: without_time
        stream: ext://sys.stderr
    stdout_console:
        class: logging.StreamHandler
        level: NOTSET
        formatter: with_time
        filters: [level]
        stream: ext://sys.stdout
    stderr_console:
        class: logging.StreamHandler
        level: WARNING
        formatter: with_time
        stream: ext://sys.stderr
    logstash:
        class: logging.handlers.RotatingFileHandler
        level: NOTSET
        formatter: with_time
        filename: c:\acode\feature-storage-bot\logs\logstash.log
#        filename: /var/log/app/logstash.log
        maxBytes: 104857600 # 100MB
        backupCount: 10
        encoding: utf8

root:
    level: WARNING
    handlers: [stdout_app, stderr_app]
    propagate: yes

loggers:
    app:
        level: NOTSET
        handlers: [logstash]
        propagate: yes
    console:
        level: NOTSET
        handlers: [stdout_console, stderr_console]
        propagate: no
