name: Build

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: licwim
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push image
      id: build-image
      run: |
        TAG=$(echo "${{ github.ref_name }}" | sed 's|/|-|g')
        IMAGE_NAME="${{ github.repository }}:$TAG"
        BUILD_VERSION="$TAG-${{ github.sha }}"
        docker build . --file Dockerfile --label sha=${{ github.sha }} --label build=$BUILD_VERSION --tag "$IMAGE_NAME"
        echo "IMAGE_NAME = $IMAGE_NAME"
        docker push "$IMAGE_NAME"
