name: Build

on:
  push:
    branches:
      - master
      - 'release/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_HUB_USERNAME: licwim
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    outputs:
      image_name: ${{ steps.build-image.outputs.IMAGE_NAME }}
      build_version: ${{ steps.build-image.outputs.BUILD_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_TOKEN }}
    - name: Build and push image
      id: build-image
      run: |
        TAG=$(if [ ${{ github.event_name }} = 'pull_request' ]; then echo "${{ github.head_ref }}"; else echo "${{ github.ref_name }}"; fi | sed 's|/|-|g')
        IMAGE_NAME="${{ github.repository }}:$TAG"
        BUILD_VERSION="$TAG-${{ github.sha }}"
        echo "BUILD_VERSION = $BUILD_VERSION"
        docker build . --file Dockerfile --label sha=${{ github.sha }} --label build=$BUILD_VERSION --tag "$IMAGE_NAME"
        echo "IMAGE_NAME = $IMAGE_NAME"
        docker push "$IMAGE_NAME"
        echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"
        echo "::set-output name=BUILD_VERSION::$BUILD_VERSION"
