name: Feature Storage Bot

on:
  push:
    branches:
      - master

jobs:
  build_and_run:
    runs-on: self-hosted
    environment: production
    env:
      CONTAINER_NAME: feature-storage-bot-app
      NETWORK_NAME: feature-storage-bot-network
      BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      API_ID: ${{ secrets.TELEGRAM_API_ID }}
      API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      ROLLBACK_PREFIX: fsb_
    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
    - name: Move configs to project folder
      run: cp -rT ../../admin .
    - name: Build the Docker image
      run: |
        IMAGE_NAME="${{ github.repository }}:$SHA"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag "$IMAGE_NAME"
    - name: Prepare rollback Docker container
      id: rollback
      run: |
        ROLLBACK_NAME=\
        "$ROLLBACK_PREFIX"\
        $(docker inspect \
          --format='{{.Config.Image}}' \
          "$CONTAINER_NAME" \
          | awk -F':' '{print $2}')
        docker rename "$CONTAINER_NAME" "$ROLLBACK_NAME"
        echo "ROLLBACK_NAME=$ROLLBACK_NAME" >> $GITHUB_ENV
    - name: Start app Docker container
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        ROLLBACK_NAME: ${{ env.rollback_name }}
      run: |
        docker stop "$ROLLBACK_NAME"
        docker run \
          --log-driver=journald \
          -e BOT_TOKEN="$BOT_TOKEN" \
          -e API_ID="$API_ID" \
          -e API_HASH="$API_HASH" \
          -e DB_PASSWORD="$DB_PASSWORD" \
          -d \
          --network "$NETWORK_NAME" \
          --name "$CONTAINER_NAME" \
          "$IMAGE_NAME"
