name: Feature Storage Bot

on:
  push:
    branches:
      - master
      - 'release/**'

jobs:
  build:
    runs-on: self-hosted
    environment: production
    outputs:
      image_name: ${{ steps.build-image.outputs.IMAGE_NAME }}
      build_version: ${{ steps.build-image.outputs.BUILD_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
    - name: Move configs to project folder
      run: cp -rT ../../admin .
    - name: Build the Docker image
      id: build-image
      run: |
        IMAGE_NAME="${{ github.repository }}:$SHA"
        BUILD_VERSION=$(echo "${{ github.ref_name }}-${{ github.sha }}" | sed 's|/|-|g')
        docker build . --file Dockerfile --label branch=${{ github.ref_name }} --tag "$IMAGE_NAME"
        echo $IMAGE_NAME
        echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"
        echo "::set-output name=BUILD_VERSION::$BUILD_VERSION"
  run:
    needs: build
    runs-on: self-hosted
    environment: production
    env:
      CONTAINER_NAME: fsb-app
      IMAGE_NAME: ${{ needs.build.outputs.image_name }}
      BUILD_VERSION: ${{ needs.build.outputs.build_version }}
      NETWORK_NAME: feature-storage-bot-network
      BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      API_ID: ${{ secrets.TELEGRAM_API_ID }}
      API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      ROLLBACK_PREFIX: fsb-bak-
    steps:
    - name: Prepare rollback Docker container
      id: rollback
      run: |
        ROLLBACK_NAME=\
        "$ROLLBACK_PREFIX"\
        $(docker inspect \
          --format='{{.Config.Image}}' \
          "$CONTAINER_NAME" \
          | awk -F':' '{print $2}')
        docker rename "$CONTAINER_NAME" "$ROLLBACK_NAME"
        echo "ROLLBACK_NAME=$ROLLBACK_NAME" >> $GITHUB_ENV
    - name: Start app Docker container
      env:
        ROLLBACK_NAME: ${{ env.ROLLBACK_NAME }}
      run: |
        docker stop "$ROLLBACK_NAME"
        docker run \
          --log-driver=journald \
          --label branch=${{ github.ref_name }} \
          -e BOT_TOKEN="$BOT_TOKEN" \
          -e API_ID="$API_ID" \
          -e API_HASH="$API_HASH" \
          -e DB_PASSWORD="$DB_PASSWORD" \
          -e BUILD_VERSION="$BUILD_VERSION" \
          -d \
          --network "$NETWORK_NAME" \
          --name "$CONTAINER_NAME" \
          "$IMAGE_NAME"
