name: Feature Storage Bot

on:
  push:
    branches:
      - dev
  pull_request_target:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    environment: production
    env:
      IMAGE_NAME: ${GITHUB_REPOSITORY}:${GITHUB_SHA::8}
      CONTAINER_NAME: feature-storage-bot-app
      WORK_DIR: /var/apps/feature_storage_bot
      BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      API_ID: ${{ secrets.TELEGRAM_API_ID }}
      API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
    steps:
    - uses: actions/checkout@v2
    - name: Place check
      run: pwd && ls -la && git status
    - name: Move configs to project folder
      run: cp -rT ../../admin .
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "$IMAGE_NAME"
    - name: Re-Run Docker container
      run: |
        docker stop "$CONTAINER_NAME"
        docker rm "$CONTAINER_NAME"
        docker run -e BOT_TOKEN="$BOT_TOKEN" -e API_ID="$API_ID" -e API_HASH="$API_HASH" -d --name "$CONTAINER_NAME" "$IMAGE_NAME"
